### ISSUE TITLE
Requesting to include [spacebar] to toggle select and edit mode in DTXCreator

### ISSUE THREAD

**Issue by approvedtx** [limyz/DTXmaniaNX#101]
First I want to apologize because this is a selfish request. I've always been using an older version of DTXCreator which allows spacebar to toggle between select mode and edit mode. The default key for this function in current version is the F8 key, but I still unable to get used to it, so I am reluctant to use the new DTXCreator as well. I Therefore I am requesting to include spacebar for this function as well. Thank you!

**Comment by limyz** [comment]
This was previously implemented years ago, need to dig code

**Comment by fisyher** [comment]
Previous code was done incorrectly. It overrode all Spacebar inputs, including those for text fields like song title and artist. Need to find a different way to implement.

**Comment by fisyher** [comment]
Windows.Form designer does not allow Space as Menu Shortcut Key, next best option is Ctrl+Space and has been accepted by @approvedtx
