### ISSUE TITLE
Damage level for guitar / bass to be improved

### ISSUE THREAD

**Issue by approvedtx** [limyz/DTXmaniaNX#105]
I would like to suggest that the damage level in guitar / bass to be made similar to arcade GuitarFreaks.
It is was too great compared to arcade.

Number of consecutive notes to stage fail (from start of song) in NX as tested:
Small - 30 notes
Normal - 15 notes
Large - 10 notes

Number of consecutive notes to stage fail (from start of song) in GuitarFreaks (NORMAL):
about 70 notes

Therefore I would like to suggest:
Small - 140 notes
Normal - 70 notes
Large - 40 notes

**Comment by fisyher** [comment]
It's more complicated than just number of consecutive missed notes. In actual Gitadora, my theory is that there is some sort of damage scaling based on total number of notes or density for that song. 

I tried playing a lvl 1 song with 122 notes and the gauge just disappears after around 30 notes. 

140 notes for Small damage level is way too high, I suggest for now just half the damage overall, meaning the number missed notes required to fail a song from the start will be:
Small - 60 notes
Normal - 30 notes
Large - 20 notes

 For more accurate damage calculation, will need to do more research.
