### ISSUE TITLE
DTXCreator Viewer crash with presence exception

### ISSUE THREAD

**Issue by ericpignet** [limyz/DTXmaniaNX#106]
![image](https://user-images.githubusercontent.com/288517/114270119-ff38bd80-9a4d-11eb-8e26-2555566f19fc.png)
DTX Creator NX 1.2.0 with DTXManiGR.exe viewer, crash when clicking on play.

**Comment by limyz** [comment]
We had this problem with DTXmania but was fixed by @fisyher on the previous release by limiting the number of characters during file parsing

**Comment by ericpignet** [comment]
OK good it was fixed on DTXMania.
I think there are actually multiple 'null reference exceptions' when DXMania is used as Viewer at the moment, I just reproduced the one mentioned in Discord:
![image](https://user-images.githubusercontent.com/288517/114272013-935b5280-9a57-11eb-8e0e-7f1923c1ea54.png)

I'm preparing a pull request with a few fixes.
