### ISSUE TITLE
Assigning "enter" key to for Pauseing a song stops you from navigating the menu

### ISSUE THREAD

**Issue by mictibo** [limyz/DTXmaniaNX#114]
It seems as the assignation of the enter Key also gets mapped in the menu areas

**Comment by fisyher** [comment]
To avoid any issues with lost of Control, both the Enter and Esc keys should not be mappable to any functions other than their intended functions.

**Comment by mictibo** [comment]
I believe it is already this for the arrow keys.
But can't there be a way to have it mapped to something different when in menus or when in songs ?

**Comment by limyz** [comment]
`Enter` is an universally accepted input for applications and should not be mappable. I don't see this an issue unless you are using a 60% keyboard

**Comment by fisyher** [comment]
Game has already disallowed several keys from being assignable: Esc, Delete and the 4 arrow keys. Added the big `Enter` aka `Return` key to this list.
