### ISSUE TITLE
Logic for drum RandomPad is wrong in 6-lane mode

### ISSUE THREAD

**Issue by sakamoto-neko** [limyz/DTXmaniaNX#116]
Shown here is Hoshi no Kakera with RandomPad set to "On" and NumOfLanes set to "6". When these settings are applied, the low-tom roll becomes an alternating hi-tom/low-tom roll as shown here: https://youtu.be/VIMPTc1R5II

This should be the correct effect, in another fork of DTXMania: https://youtu.be/9tk0eQnaPaU
The link for this particular fork is here:  http://www.mediafire.com/?t6m8r9m2wkv9v

**Comment by fisyher** [comment]
This bug has nothing to do with any Random option but has to do with the fact that Low Tom are always mapped to alternating Low and High-Toms when NumOfLanes is set to "6" aka Classic Mode.

An easy way to reproduce is simply create a chart with all Low-Toms and play it in Classic Mode.

Code that causes this effect is in CDTX.cs around Line 2125:

```C#
...
case EChannel.LowTom:
  if (num5 != chip.nPlaybackPosition)
  {
	  if (flag)
	  {
		  chip.nChannelNumber = EChannel.HighTom;
	  }
  }
  if (num3 == EChannel.LowTom)
  {
	  chip.nChannelNumber = EChannel.HighTom; //This line
  }
  num3 = chip.nChannelNumber;
  num5 = chip.nPlaybackPosition;
  continue;
```
