### ISSUE TITLE
Adding Fast Reload Songs Option in Config

### ISSUE THREAD

**Issue by approvedtx** [limyz/DTXmaniaNX#141]
Just like what AL has, NX currently only has Reload Songs (which does a Full Reload which takes super long if you have thousands of songs). Adding a Fast Reload will be useful if you want to add songs without restarting DTXMania .

**Comment by fisyher** [comment]
Fast Reload is a AL-specific feature that improves loading performance. I do not know exactly how it is done in AL but I am certain it would require major overhaul of how assets are being loaded into the program.

**Comment by fisyher** [comment]
Added in 1.4.1
