### ISSUE TITLE
Malware has been Detected

### ISSUE THREAD

**Issue by JerryDaga** [limyz/DTXmaniaNX#145]
I worry regarding on NX version because have detected on anti-virus and malware so I did not install that :(
Do you have a portable version (not Installer base) and without malware built in

**Comment by limyz** [comment]
this is a serious issue not to be taken lightly, our code is open for review. please provide evidence for stating so, else you may proceed to compile from source.

![image](https://user-images.githubusercontent.com/8562888/159160034-da859f4b-137a-4a75-a1b8-19c8bbb3b975.png)
if you are refering to smartscreen, you run anyway to proceed installation.

**Comment by JerryDaga** [comment]
here is the photo sample at the upper right on the screen.[image: image.png]
[image: image.png]

[image: image.png]
