### ISSUE TITLE
App crashes after every cleared stage screen. Stage Fail screen did't crash

### ISSUE THREAD

**Issue by AlexKomrakov** [limyz/DTXmaniaNX#155]
![image](https://user-images.githubusercontent.com/7386252/197385870-b27fe843-f696-452a-98ae-7ef86d11de5a.png)

Windows 11.
Tested several times with default settings
- clear 1.40 installation from github - error
- 1.40 with high voltage skin - error
- furukon starter pack 1.40 - error
- **1.30 from github - no error**

**Comment by amaddula** [comment]
![image](https://github.com/limyz/DTXmaniaNX/assets/25397273/fdd51810-7632-4664-be11-eee78660019d)
I have the same issue in Windows 11 with the latest version of DTXManiaNX.

**Comment by amaddula** [comment]
I managed to fix it! Go to this youtube video by Furukon: https://www.youtube.com/watch?v=95V932uzowo&list=PLj22ny7-DS2V-l0pWLhp8cLRYLF3jskCs&index=2

In the description, (5) denotes to download DirectX Redist for a d3dx39 error. The installer is available in the google drive link. After downloading this, and restarting DTXManiaNX twice and resetting the latency through ASIO4ALL (https://www.youtube.com/watch?v=lMjwAq-vQwU&list=PLj22ny7-DS2V-l0pWLhp8cLRYLF3jskCs&index=9), I am no longer crashing after stage completion.
