### ISSUE TITLE
DTXmaniaNX 1.4.1 Skins

### ISSUE THREAD

**Issue by Christian7600000** [limyz/DTXmaniaNX#172]
Excuse me, Implementing Skins for DTXmaniaNX 1.4.1 Is A Good Idea OK

**Comment by Christian7600000** [comment]
Then WIll Be Another Month

**Comment by Christian7600000** [comment]
Updating

**Comment by fisyher** [comment]
@Christian7600000 This place is for posting issues such as bugs, feature request, suggestions for improvements for DTXManiaNX, not a Discord chat channel. Please post on DTXMania Discord if you have any general queries or just want to chat about it.
