### ISSUE TITLE
The new DTXMania version doesnt display the song artist name correctly in the loading screen and during gameplay for some songs

### ISSUE THREAD

**Issue by Chronon1cal** [limyz/DTXmaniaNX#54]

**Comment by ericpignet** [comment]
From Discord:
![image](https://user-images.githubusercontent.com/288517/93877010-1bc41100-fd1b-11ea-9ab1-791d7a912b64.png)
![image](https://user-images.githubusercontent.com/288517/93877042-27afd300-fd1b-11ea-9c8e-95ba8eed1d0f.png)

**Comment by fisyher** [comment]
This issue is caused by certain font type not able to draw some Japanese characters. Please choose a font that officially supports Japanese characters where possible.
