### ISSUE TITLE
Can select non-existent instrument parts in charts without instrument present

### ISSUE THREAD

**Issue by 987123879113** [limyz/DTXmaniaNX#67]
For example, in a .dtx file with only guitar and bass, it is possible to select drums. The guitar and bass charts will autoplay in the background while the screen scrolls with no chips for the entire duration of the song which is not very useful and doesn't make much sense.

If an instrument does not exist in the chart then ideally it should not be selectable.

**Comment by fisyher** [comment]
Done. Besides normal song select, I also have updated Random Select to prevent being able to select non-existent part of a song.
