### ISSUE TITLE
Only one sound can be played at anytime on the same SE lane

### ISSUE THREAD

**Issue by approvedtx** [limyz/DTXmaniaNX#69]
For example if there's a cymbal keysound chip placed on lane SE1, and a 2nd chip gets placed on the same lane right after when the cymbal keysound is still playing, the cymbal keysound gets muted and starts to play the 2nd chip. Right now, the only solution is to shift consecutive chips to other lanes to prevent premature muting of these sounds.

**Comment by fisyher** [comment]
There are a total of 32 SE channels but only 5 are visible by default in DTXCreator. The remaining SE6 to SE32 can be made visible by enabling the SE6_32 checkbox in Option/Lanes menu, which is unchecked by default. I think most DTX creators would be unaware of this and use only SE1 to SE5 with existing behaviour.

For the fix, wav playback for SE1 to SE5 will keep the same behavior to maintain backward compatibility with most charts. The extra channels SE6 to SE32 will be updated to play consecutive wav sounds without interruption.
