### ISSUE TITLE
Description for "ShowLagTimeColor" configuration is flipped

### ISSUE THREAD

**Issue by fisyher** [limyz/DTXmaniaNX#70]
According to the description, Type-A shows early note in Red and late notes in Blue, and vice versa:

![image](https://user-images.githubusercontent.com/15701545/94815112-c1b70000-042c-11eb-814d-250470296858.png)

However, if you actually play the game, it is actually the opposite based on what I understood from the description: Early note means that you have hit the note too early and Late note means you have hit the note too late.

It is possible that others may interpret this description differently: Early means you have to hit earlier and Late means you have to hit later. Personally, I find this interpretation very confusing and misleading though.

Please share your opinions on this and how best we can update this description.

**Comment by ericpignet** [comment]
I understand it the same way as you and I think we should fix the description in the Config menu. Either swap red and blue, or swap early and late.
The description in the Config.ini file (in Japanese) seems correct.

**Comment by fisyher** [comment]
OK. I will update accordingly, just simply swapping the Early and Late around.
