### ISSUE TITLE
Enable/Disable DirectX Exclusive mode

### ISSUE THREAD

**Issue by furukon** [limyz/DTXmaniaNX#88]
I would like to propose something that will enable or disable DX Exclusive mode. DX Exclusive mode is when you press ALT+ENTER to exit full screen mode, but there will be a few seconds of a black screen. On games nowdays, exiting full screen mode will immediately show the game in window mode, and this will really be useful for switching windows when doing other tasks, and will be useful for users using just one monitor.

**Comment by ericpignet** [comment]
Thanks for opening the ticket... but I've just implemented this already via ticket #85  ;-)

**Comment by ericpignet** [comment]
A new config option FullScreenExclusive was added to Config.ini.
If set to 0, use maximized window, so the Alt+Enter switch is much faster
If set to 1 (default value), keep using DirectX exclusive mode
