### ISSUE TITLE
Installer for DTXManiaNX

### ISSUE THREAD

**Issue by retorquere** [limyz/DTXmaniaNX#97]
For the less technical of my friends, an installer would be great. I've created an InnoSetup install script at https://gist.github.com/retorquere/4416161df1c71188d006146e9f1f9d9b. It installs into the user appdata instead of `Program Files` so that the user can upload tracks to the install dir, that way de config.ini can stay as it is.

**Comment by ericpignet** [comment]
That's great contribution, thanks!
I personally don't know much about InnoSetup, and I'm not handling the packaging of DTXMania, so I will leave this to other contributors, but I agree it's a nice addition for less technical users.

**Comment by retorquere** [comment]
I haven't used InnoSetup in ages, but it's the simplest installer-builder I know.

Who does handle the packaging? Is that on another repo?

**Comment by fisyher** [comment]
It is not allowed for third-party publisher to distribute both Microsoft .NET framework and dxwebsetup.exe as part of the installer package. Instead we can redirect the installer wizard to download from official download sites and install. 

I have found a smart Inno Setup script that does exactly that and modified it according to the requirements for DTXManiaNX. Installer will be made available starting next release.
